### ISSUE TITLE
Really? Kuvernetes?

### ISSUE THREAD

**Issue by dfradehubs** [freepik-company/admitik#5]
https://github.com/freepik-company/admitik/blob/416d598b7d7144639ff3a0320981cb4d4bff9482/internal/admission/server.go#L250C47-L250C56

**Comment by achetronic** [comment]
https://m.youtube.com/watch?v=kTzuEB82hFs&t=11s&pp=2AELkAIB

It doesn't matter as no one pronounce it properly 🤯😂
